/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';

/**
* ImageImageSuperResolution service.
* @module api/ImageImageSuperResolutionApi
* @version 0.1.0
*/
export default class ImageImageSuperResolutionApi {

    /**
    * Constructs a new ImageImageSuperResolutionApi. 
    * @alias module:api/ImageImageSuperResolutionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the applyImageImageSuperResolutionPost operation.
     * @callback module:api/ImageImageSuperResolutionApi~applyImageImageSuperResolutionPostCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Apply model for the super-resolution task for a given models
     * @param {File} image 
     * @param {Object} opts Optional parameters
     * @param {String} opts.model  (default to 'esrgan')
     * @param {module:api/ImageImageSuperResolutionApi~applyImageImageSuperResolutionPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    applyImageImageSuperResolutionPost(image, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'image' is set
      if (image === undefined || image === null) {
        throw new Error("Missing the required parameter 'image' when calling applyImageImageSuperResolutionPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'model': opts['model']
      };
      let headerParams = {
      };
      let formParams = {
        'image': image
      };

      let authNames = [];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/image/image/super-resolution/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVersionsImageImageSuperResolutionGet operation.
     * @callback module:api/ImageImageSuperResolutionApi~getVersionsImageImageSuperResolutionGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list of models available for super-resolution
     * @param {module:api/ImageImageSuperResolutionApi~getVersionsImageImageSuperResolutionGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getVersionsImageImageSuperResolutionGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/image/image/super-resolution/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
