import * as api from './api/api';
import * as angular from 'angular';

const apiModule = angular.module('api', [])
.service('ImageImageBackgroundRemovalApi', api.ImageImageBackgroundRemovalApi)
.service('ImageImageColorizationApi', api.ImageImageColorizationApi)
.service('ImageImageFaceBluringApi', api.ImageImageFaceBluringApi)
.service('ImageImageRestorationApi', api.ImageImageRestorationApi)
.service('ImageImageSuperResolutionApi', api.ImageImageSuperResolutionApi)
.service('ImageImageUncolorizationApi', api.ImageImageUncolorizationApi)
.service('TextTextAutocorrectApi', api.TextTextAutocorrectApi)
.service('TextTextBooleanQuestionGenerationApi', api.TextTextBooleanQuestionGenerationApi)
.service('TextTextDependencyTrackingApi', api.TextTextDependencyTrackingApi)
.service('TextTextEmotionRecognitionApi', api.TextTextEmotionRecognitionApi)
.service('TextTextEntityExtractionApi', api.TextTextEntityExtractionApi)
.service('TextTextHateSpeechDetectionApi', api.TextTextHateSpeechDetectionApi)
.service('TextTextKeywordExtractionApi', api.TextTextKeywordExtractionApi)
.service('TextTextLanguageDetectionApi', api.TextTextLanguageDetectionApi)
.service('TextTextLanguageGenerationApi', api.TextTextLanguageGenerationApi)
.service('TextTextLemmatizationApi', api.TextTextLemmatizationApi)
.service('TextTextNamedEntityRecognitionApi', api.TextTextNamedEntityRecognitionApi)
.service('TextTextNextSentencePredictionApi', api.TextTextNextSentencePredictionApi)
.service('TextTextNextWordPredictionApi', api.TextTextNextWordPredictionApi)
.service('TextTextPluralApi', api.TextTextPluralApi)
.service('TextTextProgrammingLanguageGenerationApi', api.TextTextProgrammingLanguageGenerationApi)
.service('TextTextProgrammingLanguageIdentificationApi', api.TextTextProgrammingLanguageIdentificationApi)
.service('TextTextQuestionAnsweringApi', api.TextTextQuestionAnsweringApi)
.service('TextTextSentencePairModelingApi', api.TextTextSentencePairModelingApi)
.service('TextTextSentenceParaphraserApi', api.TextTextSentenceParaphraserApi)
.service('TextTextSentimentAnalysisApi', api.TextTextSentimentAnalysisApi)
.service('TextTextSimilarityApi', api.TextTextSimilarityApi)
.service('TextTextSummarizationApi', api.TextTextSummarizationApi)
.service('TextTextTranslationApi', api.TextTextTranslationApi)
.service('TextTextTransliterationApi', api.TextTextTransliterationApi)
.service('TextTextWordAlignmentApi', api.TextTextWordAlignmentApi)

export default apiModule;
