/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBody_apply_image_image_background_removal__post.h
 *
 * 
 */

#ifndef OAIBody_apply_image_image_background_removal__post_H
#define OAIBody_apply_image_image_background_removal__post_H

#include <QJsonObject>


#include "OAIHttpRequest.h"

#include "OAIObject.h"
#include "OAIEnum.h"

namespace OpenAPI {

class OAIBody_apply_image_image_background_removal__post: public OAIObject {
public:
    OAIBody_apply_image_image_background_removal__post();
    OAIBody_apply_image_image_background_removal__post(QString json);
    ~OAIBody_apply_image_image_background_removal__post() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    OAIHttpRequestInputFileElement* getImage() const;
    void setImage(const OAIHttpRequestInputFileElement* &image);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    OAIHttpRequestInputFileElement* image;
    bool m_image_isSet;
    bool m_image_isValid;
    
    };

}

#endif // OAIBody_apply_image_image_background_removal__post_H
