/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAITextTextSentimentAnalysisApi_H
#define OAI_OAITextTextSentimentAnalysisApi_H

#include "OAIHttpRequest.h"

#include "OAIHTTPValidationError.h"
#include "OAIObject.h"
#include <QString>

#include <QObject>

namespace OpenAPI {

class OAITextTextSentimentAnalysisApi: public QObject {
    Q_OBJECT

public:
    OAITextTextSentimentAnalysisApi();
    OAITextTextSentimentAnalysisApi(QString host, QString basePath);
    ~OAITextTextSentimentAnalysisApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void applyTextTextSentimentAnalysisPost(const QString& text, const QString& model);
    void getVersionsTextTextSentimentAnalysisGet();
    
private:
    void applyTextTextSentimentAnalysisPostCallback (OAIHttpRequestWorker * worker);
    void getVersionsTextTextSentimentAnalysisGetCallback (OAIHttpRequestWorker * worker);
    
signals:
    void applyTextTextSentimentAnalysisPostSignal(OAIObject summary);
    void getVersionsTextTextSentimentAnalysisGetSignal(OAIObject summary);
    
    void applyTextTextSentimentAnalysisPostSignalFull(OAIHttpRequestWorker* worker, OAIObject summary);
    void getVersionsTextTextSentimentAnalysisGetSignalFull(OAIHttpRequestWorker* worker, OAIObject summary);
    
    void applyTextTextSentimentAnalysisPostSignalE(OAIObject summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void getVersionsTextTextSentimentAnalysisGetSignalE(OAIObject summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void applyTextTextSentimentAnalysisPostSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void getVersionsTextTextSentimentAnalysisGetSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
