/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITextTextTransliterationApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAITextTextTransliterationApi::OAITextTextTransliterationApi() {

}

OAITextTextTransliterationApi::~OAITextTextTransliterationApi() {

}

OAITextTextTransliterationApi::OAITextTextTransliterationApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAITextTextTransliterationApi::applyTextTextTransliterationPost(const QString& text, const QString& language, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/transliteration/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("text"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(text)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("language"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(language)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextTransliterationApi::applyTextTextTransliterationPostCallback);

    worker->execute(&input);
}

void
OAITextTextTransliterationApi::applyTextTextTransliterationPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyTextTextTransliterationPostSignal(output);
        emit applyTextTextTransliterationPostSignalFull(worker, output);
    } else {
        emit applyTextTextTransliterationPostSignalE(output, error_type, error_str);
        emit applyTextTextTransliterationPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAITextTextTransliterationApi::getVersionsTextTextTransliterationGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/transliteration/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextTransliterationApi::getVersionsTextTextTransliterationGetCallback);

    worker->execute(&input);
}

void
OAITextTextTransliterationApi::getVersionsTextTextTransliterationGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsTextTextTransliterationGetSignal(output);
        emit getVersionsTextTextTransliterationGetSignalFull(worker, output);
    } else {
        emit getVersionsTextTextTransliterationGetSignalE(output, error_type, error_str);
        emit getVersionsTextTextTransliterationGetSignalEFull(worker, error_type, error_str);
    }
}


}
