/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITextTextProgrammingLanguageGenerationApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAITextTextProgrammingLanguageGenerationApi::OAITextTextProgrammingLanguageGenerationApi() {

}

OAITextTextProgrammingLanguageGenerationApi::~OAITextTextProgrammingLanguageGenerationApi() {

}

OAITextTextProgrammingLanguageGenerationApi::OAITextTextProgrammingLanguageGenerationApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAITextTextProgrammingLanguageGenerationApi::applyTextTextProgrammingLanguageGenerationPost(const QString& code_snippet, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/programming-language-generation/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("code_snippet"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(code_snippet)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextProgrammingLanguageGenerationApi::applyTextTextProgrammingLanguageGenerationPostCallback);

    worker->execute(&input);
}

void
OAITextTextProgrammingLanguageGenerationApi::applyTextTextProgrammingLanguageGenerationPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyTextTextProgrammingLanguageGenerationPostSignal(output);
        emit applyTextTextProgrammingLanguageGenerationPostSignalFull(worker, output);
    } else {
        emit applyTextTextProgrammingLanguageGenerationPostSignalE(output, error_type, error_str);
        emit applyTextTextProgrammingLanguageGenerationPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAITextTextProgrammingLanguageGenerationApi::getVersionsTextTextProgrammingLanguageGenerationGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/programming-language-generation/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextProgrammingLanguageGenerationApi::getVersionsTextTextProgrammingLanguageGenerationGetCallback);

    worker->execute(&input);
}

void
OAITextTextProgrammingLanguageGenerationApi::getVersionsTextTextProgrammingLanguageGenerationGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsTextTextProgrammingLanguageGenerationGetSignal(output);
        emit getVersionsTextTextProgrammingLanguageGenerationGetSignalFull(worker, output);
    } else {
        emit getVersionsTextTextProgrammingLanguageGenerationGetSignalE(output, error_type, error_str);
        emit getVersionsTextTextProgrammingLanguageGenerationGetSignalEFull(worker, error_type, error_str);
    }
}


}
