/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAITextTextProgrammingLanguageGenerationApi_H
#define OAI_OAITextTextProgrammingLanguageGenerationApi_H

#include "OAIHttpRequest.h"

#include "OAIHTTPValidationError.h"
#include "OAIObject.h"
#include <QString>

#include <QObject>

namespace OpenAPI {

class OAITextTextProgrammingLanguageGenerationApi: public QObject {
    Q_OBJECT

public:
    OAITextTextProgrammingLanguageGenerationApi();
    OAITextTextProgrammingLanguageGenerationApi(QString host, QString basePath);
    ~OAITextTextProgrammingLanguageGenerationApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void applyTextTextProgrammingLanguageGenerationPost(const QString& code_snippet, const QString& model);
    void getVersionsTextTextProgrammingLanguageGenerationGet();
    
private:
    void applyTextTextProgrammingLanguageGenerationPostCallback (OAIHttpRequestWorker * worker);
    void getVersionsTextTextProgrammingLanguageGenerationGetCallback (OAIHttpRequestWorker * worker);
    
signals:
    void applyTextTextProgrammingLanguageGenerationPostSignal(OAIObject summary);
    void getVersionsTextTextProgrammingLanguageGenerationGetSignal(OAIObject summary);
    
    void applyTextTextProgrammingLanguageGenerationPostSignalFull(OAIHttpRequestWorker* worker, OAIObject summary);
    void getVersionsTextTextProgrammingLanguageGenerationGetSignalFull(OAIHttpRequestWorker* worker, OAIObject summary);
    
    void applyTextTextProgrammingLanguageGenerationPostSignalE(OAIObject summary, QNetworkReply::NetworkError error_type, QString& error_str);
    void getVersionsTextTextProgrammingLanguageGenerationGetSignalE(OAIObject summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void applyTextTextProgrammingLanguageGenerationPostSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    void getVersionsTextTextProgrammingLanguageGenerationGetSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
