/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITextTextDependencyTrackingApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAITextTextDependencyTrackingApi::OAITextTextDependencyTrackingApi() {

}

OAITextTextDependencyTrackingApi::~OAITextTextDependencyTrackingApi() {

}

OAITextTextDependencyTrackingApi::OAITextTextDependencyTrackingApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAITextTextDependencyTrackingApi::applyTextTextDependencyTrackingPost(const QString& input_string, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/dependency-tracking/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("input_string"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(input_string)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextDependencyTrackingApi::applyTextTextDependencyTrackingPostCallback);

    worker->execute(&input);
}

void
OAITextTextDependencyTrackingApi::applyTextTextDependencyTrackingPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyTextTextDependencyTrackingPostSignal(output);
        emit applyTextTextDependencyTrackingPostSignalFull(worker, output);
    } else {
        emit applyTextTextDependencyTrackingPostSignalE(output, error_type, error_str);
        emit applyTextTextDependencyTrackingPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAITextTextDependencyTrackingApi::getVersionsTextTextDependencyTrackingGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/dependency-tracking/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextDependencyTrackingApi::getVersionsTextTextDependencyTrackingGetCallback);

    worker->execute(&input);
}

void
OAITextTextDependencyTrackingApi::getVersionsTextTextDependencyTrackingGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsTextTextDependencyTrackingGetSignal(output);
        emit getVersionsTextTextDependencyTrackingGetSignalFull(worker, output);
    } else {
        emit getVersionsTextTextDependencyTrackingGetSignalE(output, error_type, error_str);
        emit getVersionsTextTextDependencyTrackingGetSignalEFull(worker, error_type, error_str);
    }
}


}
