/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITextTextNamedEntityRecognitionApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAITextTextNamedEntityRecognitionApi::OAITextTextNamedEntityRecognitionApi() {

}

OAITextTextNamedEntityRecognitionApi::~OAITextTextNamedEntityRecognitionApi() {

}

OAITextTextNamedEntityRecognitionApi::OAITextTextNamedEntityRecognitionApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAITextTextNamedEntityRecognitionApi::applyTextTextNamedEntityRecognitionPost(const QString& text, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/named-entity-recognition/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("text"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(text)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextNamedEntityRecognitionApi::applyTextTextNamedEntityRecognitionPostCallback);

    worker->execute(&input);
}

void
OAITextTextNamedEntityRecognitionApi::applyTextTextNamedEntityRecognitionPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyTextTextNamedEntityRecognitionPostSignal(output);
        emit applyTextTextNamedEntityRecognitionPostSignalFull(worker, output);
    } else {
        emit applyTextTextNamedEntityRecognitionPostSignalE(output, error_type, error_str);
        emit applyTextTextNamedEntityRecognitionPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAITextTextNamedEntityRecognitionApi::getVersionsTextTextNamedEntityRecognitionGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/named-entity-recognition/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextNamedEntityRecognitionApi::getVersionsTextTextNamedEntityRecognitionGetCallback);

    worker->execute(&input);
}

void
OAITextTextNamedEntityRecognitionApi::getVersionsTextTextNamedEntityRecognitionGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsTextTextNamedEntityRecognitionGetSignal(output);
        emit getVersionsTextTextNamedEntityRecognitionGetSignalFull(worker, output);
    } else {
        emit getVersionsTextTextNamedEntityRecognitionGetSignalE(output, error_type, error_str);
        emit getVersionsTextTextNamedEntityRecognitionGetSignalEFull(worker, error_type, error_str);
    }
}


}
