/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITextTextSimilarityApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAITextTextSimilarityApi::OAITextTextSimilarityApi() {

}

OAITextTextSimilarityApi::~OAITextTextSimilarityApi() {

}

OAITextTextSimilarityApi::OAITextTextSimilarityApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAITextTextSimilarityApi::applyTextTextSimilarityPost(const QString& sentence_1, const QString& sentence_2, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/similarity/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("sentence_1"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(sentence_1)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("sentence_2"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(sentence_2)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextSimilarityApi::applyTextTextSimilarityPostCallback);

    worker->execute(&input);
}

void
OAITextTextSimilarityApi::applyTextTextSimilarityPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyTextTextSimilarityPostSignal(output);
        emit applyTextTextSimilarityPostSignalFull(worker, output);
    } else {
        emit applyTextTextSimilarityPostSignalE(output, error_type, error_str);
        emit applyTextTextSimilarityPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAITextTextSimilarityApi::getVersionsTextTextSimilarityGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/similarity/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextSimilarityApi::getVersionsTextTextSimilarityGetCallback);

    worker->execute(&input);
}

void
OAITextTextSimilarityApi::getVersionsTextTextSimilarityGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsTextTextSimilarityGetSignal(output);
        emit getVersionsTextTextSimilarityGetSignalFull(worker, output);
    } else {
        emit getVersionsTextTextSimilarityGetSignalE(output, error_type, error_str);
        emit getVersionsTextTextSimilarityGetSignalEFull(worker, error_type, error_str);
    }
}


}
