/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAITextTextAutocorrectApi.h"
#include "OAIHelpers.h"

#include <QJsonArray>
#include <QJsonDocument>

namespace OpenAPI {

OAITextTextAutocorrectApi::OAITextTextAutocorrectApi() {

}

OAITextTextAutocorrectApi::~OAITextTextAutocorrectApi() {

}

OAITextTextAutocorrectApi::OAITextTextAutocorrectApi(QString host, QString basePath) {
    this->host = host;
    this->basePath = basePath;
}

void
OAITextTextAutocorrectApi::applyTextTextAutocorrectPost(const QString& sentence, const QString& model) {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/autocorrect/");
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("sentence"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(sentence)));
    
    if (fullPath.indexOf("?") > 0)
      fullPath.append("&");
    else
      fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("model"))
        .append("=")
        .append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(model)));
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "POST");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextAutocorrectApi::applyTextTextAutocorrectPostCallback);

    worker->execute(&input);
}

void
OAITextTextAutocorrectApi::applyTextTextAutocorrectPostCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit applyTextTextAutocorrectPostSignal(output);
        emit applyTextTextAutocorrectPostSignalFull(worker, output);
    } else {
        emit applyTextTextAutocorrectPostSignalE(output, error_type, error_str);
        emit applyTextTextAutocorrectPostSignalEFull(worker, error_type, error_str);
    }
}

void
OAITextTextAutocorrectApi::getVersionsTextTextAutocorrectGet() {
    QString fullPath;
    fullPath.append(this->host).append(this->basePath).append("/text/text/autocorrect/");
    
    OAIHttpRequestWorker *worker = new OAIHttpRequestWorker();
    OAIHttpRequestInput input(fullPath, "GET");


    foreach(QString key, this->defaultHeaders.keys()) {
        input.headers.insert(key, this->defaultHeaders.value(key));
    }

    connect(worker,
            &OAIHttpRequestWorker::on_execution_finished,
            this,
            &OAITextTextAutocorrectApi::getVersionsTextTextAutocorrectGetCallback);

    worker->execute(&input);
}

void
OAITextTextAutocorrectApi::getVersionsTextTextAutocorrectGetCallback(OAIHttpRequestWorker * worker) {
    QString msg;
    QString error_str = worker->error_str;
    QNetworkReply::NetworkError error_type = worker->error_type;

    if (worker->error_type == QNetworkReply::NoError) {
        msg = QString("Success! %1 bytes").arg(worker->response.length());
    }
    else {
        msg = "Error: " + worker->error_str;
    }
    OAIObject output(QString(worker->response));
    worker->deleteLater();

    if (worker->error_type == QNetworkReply::NoError) {
        emit getVersionsTextTextAutocorrectGetSignal(output);
        emit getVersionsTextTextAutocorrectGetSignalFull(worker, output);
    } else {
        emit getVersionsTextTextAutocorrectGetSignalE(output, error_type, error_str);
        emit getVersionsTextTextAutocorrectGetSignalEFull(worker, error_type, error_str);
    }
}


}
