{-
   FastAPI
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: 0.1.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.HTTPValidationError exposing (HTTPValidationError, decoder, encode)

import Data.ValidationError as ValidationError exposing (ValidationError)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias HTTPValidationError =
    { detail : Maybe ((List ValidationError))
    }


decoder : Decoder HTTPValidationError
decoder =
    Decode.succeed HTTPValidationError
        |> optional "detail" (Decode.nullable (Decode.list ValidationError.decoder)) Nothing



encode : HTTPValidationError -> Encode.Value
encode model =
    Encode.object
        [ ( "detail", Maybe.withDefault Encode.null (Maybe.map (Encode.list ValidationError.encode) model.detail) )

        ]


