/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
} from './models';

/**
 * applyTextTextWordAlignmentPost - parameters interface
 */
export interface IApplyTextTextWordAlignmentPostParams {
  inputStringLanguage1?: string;
  inputStringLanguage2?: string;
  model?: 'bert-base-multilingual-cased';
}

/**
 * getVersionsTextTextWordAlignmentGet - parameters interface
 */
export interface IGetVersionsTextTextWordAlignmentGetParams {
}

/**
 * TextTextWordAlignmentApi - API class
 */
@autoinject()
export class TextTextWordAlignmentApi extends Api {

  /**
   * Creates a new TextTextWordAlignmentApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Apply model for the word-alignment task for a given models
   * @param params.inputStringLanguage1 
   * @param params.inputStringLanguage2 
   * @param params.model 
   */
  async applyTextTextWordAlignmentPost(params: IApplyTextTextWordAlignmentPostParams): Promise<object> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/text/text/word-alignment/`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Set query parameters
      .withParams({ 
        'input_string_language_1': params['inputStringLanguage1'],
        'input_string_language_2': params['inputStringLanguage2'],
        'model': params['model'],
      })

      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Get list of models available for word-alignment
   */
  async getVersionsTextTextWordAlignmentGet(): Promise<object> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/text/text/word-alignment/`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()

      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

