from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from openapi_client.api.image_image_background_removal_api import ImageImageBackgroundRemovalApi
from openapi_client.api.image_image_colorization_api import ImageImageColorizationApi
from openapi_client.api.image_image_face_bluring_api import ImageImageFaceBluringApi
from openapi_client.api.image_image_restoration_api import ImageImageRestorationApi
from openapi_client.api.image_image_super_resolution_api import ImageImageSuperResolutionApi
from openapi_client.api.image_image_uncolorization_api import ImageImageUncolorizationApi
from openapi_client.api.text_text_autocorrect_api import TextTextAutocorrectApi
from openapi_client.api.text_text_boolean_question_generation_api import TextTextBooleanQuestionGenerationApi
from openapi_client.api.text_text_dependency_tracking_api import TextTextDependencyTrackingApi
from openapi_client.api.text_text_emotion_recognition_api import TextTextEmotionRecognitionApi
from openapi_client.api.text_text_entity_extraction_api import TextTextEntityExtractionApi
from openapi_client.api.text_text_hate_speech_detection_api import TextTextHateSpeechDetectionApi
from openapi_client.api.text_text_keyword_extraction_api import TextTextKeywordExtractionApi
from openapi_client.api.text_text_language_detection_api import TextTextLanguageDetectionApi
from openapi_client.api.text_text_language_generation_api import TextTextLanguageGenerationApi
from openapi_client.api.text_text_lemmatization_api import TextTextLemmatizationApi
from openapi_client.api.text_text_named_entity_recognition_api import TextTextNamedEntityRecognitionApi
from openapi_client.api.text_text_next_sentence_prediction_api import TextTextNextSentencePredictionApi
from openapi_client.api.text_text_next_word_prediction_api import TextTextNextWordPredictionApi
from openapi_client.api.text_text_plural_api import TextTextPluralApi
from openapi_client.api.text_text_programming_language_generation_api import TextTextProgrammingLanguageGenerationApi
from openapi_client.api.text_text_programming_language_identification_api import TextTextProgrammingLanguageIdentificationApi
from openapi_client.api.text_text_question_answering_api import TextTextQuestionAnsweringApi
from openapi_client.api.text_text_sentence_pair_modeling_api import TextTextSentencePairModelingApi
from openapi_client.api.text_text_sentence_paraphraser_api import TextTextSentenceParaphraserApi
from openapi_client.api.text_text_sentiment_analysis_api import TextTextSentimentAnalysisApi
from openapi_client.api.text_text_similarity_api import TextTextSimilarityApi
from openapi_client.api.text_text_summarization_api import TextTextSummarizationApi
from openapi_client.api.text_text_translation_api import TextTextTranslationApi
from openapi_client.api.text_text_transliteration_api import TextTextTransliterationApi
from openapi_client.api.text_text_word_alignment_api import TextTextWordAlignmentApi
