//
// HTTPValidationError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


open class HTTPValidationError: JSONEncodable {

    public var detail: [ValidationError]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["detail"] = self.detail?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

