//
// TextTextSummarizationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire


open class TextTextSummarizationAPI: APIBase {
    /**
     * enum for parameter model
     */
    public enum Model_applyTextTextSummarizationPost: String { 
        case distilbartCnn126 = "distilbart-cnn-12-6"
    }

    /**
     Apply model for the summarization task for a given models
     - parameter text: (query)  (optional)
     - parameter sourceLanguage: (query)  (optional)
     - parameter maxLength: (query)  (optional)
     - parameter minLength: (query)  (optional)
     - parameter model: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func applyTextTextSummarizationPost(text: String? = nil, sourceLanguage: String? = nil, maxLength: Int32? = nil, minLength: Int32? = nil, model: Model_applyTextTextSummarizationPost? = nil, completion: @escaping ((_ data: Any?, _ error: ErrorResponse?) -> Void)) {
        applyTextTextSummarizationPostWithRequestBuilder(text: text, sourceLanguage: sourceLanguage, maxLength: maxLength, minLength: minLength, model: model).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Apply model for the summarization task for a given models
     - POST /text/text/summarization/
     - parameter text: (query)  (optional)
     - parameter sourceLanguage: (query)  (optional)
     - parameter maxLength: (query)  (optional)
     - parameter minLength: (query)  (optional)
     - parameter model: (query)  (optional)
     - returns: RequestBuilder<Any> 
     */
    open class func applyTextTextSummarizationPostWithRequestBuilder(text: String? = nil, sourceLanguage: String? = nil, maxLength: Int32? = nil, minLength: Int32? = nil, model: Model_applyTextTextSummarizationPost? = nil) -> RequestBuilder<Any> {
        let path = "/text/text/summarization/"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "text": text,
            "source_language": sourceLanguage,
            "max_length": maxLength?.encodeToJSON(),
            "min_length": minLength?.encodeToJSON(),
            "model": model?.rawValue
        ])

        let requestBuilder: RequestBuilder<Any>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get list of models available for summarization
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getVersionsTextTextSummarizationGet(completion: @escaping ((_ data: Any?, _ error: ErrorResponse?) -> Void)) {
        getVersionsTextTextSummarizationGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get list of models available for summarization
     - GET /text/text/summarization/
     - returns: RequestBuilder<Any> 
     */
    open class func getVersionsTextTextSummarizationGetWithRequestBuilder() -> RequestBuilder<Any> {
        let path = "/text/text/summarization/"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Any>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
