//
// TextTextHateSpeechDetectionAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Alamofire



public class TextTextHateSpeechDetectionAPI: APIBase {
    /**
     Apply model for the hate-speech-detection task for a given models
     
     - parameter text: (query)  (optional)
     - parameter model: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func applyTextTextHateSpeechDetectionPost(text text: String? = nil, model: String? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        applyTextTextHateSpeechDetectionPostWithRequestBuilder(text: text, model: model).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Apply model for the hate-speech-detection task for a given models
     - POST /text/text/hate-speech-detection/     - parameter text: (query)  (optional)
     - parameter model: (query)  (optional)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func applyTextTextHateSpeechDetectionPostWithRequestBuilder(text text: String? = nil, model: String? = nil) -> RequestBuilder<AnyObject> {
        let path = "/text/text/hate-speech-detection/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "text": text,
            "model": model
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get list of models available for hate-speech-detection
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getVersionsTextTextHateSpeechDetectionGet(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        getVersionsTextTextHateSpeechDetectionGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get list of models available for hate-speech-detection
     - GET /text/text/hate-speech-detection/
     - returns: RequestBuilder<AnyObject> 
     */
    public class func getVersionsTextTextHateSpeechDetectionGetWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/text/text/hate-speech-detection/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
