//
// TextTextSentimentAnalysisAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Alamofire



public class TextTextSentimentAnalysisAPI: APIBase {
    /**
     * enum for parameter model
     */
    public enum Model_applyTextTextSentimentAnalysisPost: String { 
        case NlptownBertBaseMultilingualUncasedSentiment = "nlptown-bert-base-multilingual-uncased-sentiment"
        case DistilbertBaseUncased = "distilbert-base-uncased"
        case DistilbertBaseUncasedFinetunedSst2English = "distilbert-base-uncased-finetuned-sst-2-english"
        case ZeroShotClassificationFacebookBartLargeMnli = "zero-shot-classification-facebook-bart-large-mnli"
    }

    /**
     Apply model for the sentiment-analysis task for a given models
     
     - parameter text: (query)  (optional)
     - parameter model: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func applyTextTextSentimentAnalysisPost(text text: String? = nil, model: Model_applyTextTextSentimentAnalysisPost? = nil, completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        applyTextTextSentimentAnalysisPostWithRequestBuilder(text: text, model: model).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Apply model for the sentiment-analysis task for a given models
     - POST /text/text/sentiment-analysis/     - parameter text: (query)  (optional)
     - parameter model: (query)  (optional)

     - returns: RequestBuilder<AnyObject> 
     */
    public class func applyTextTextSentimentAnalysisPostWithRequestBuilder(text text: String? = nil, model: Model_applyTextTextSentimentAnalysisPost? = nil) -> RequestBuilder<AnyObject> {
        let path = "/text/text/sentiment-analysis/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "text": text,
            "model": model?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get list of models available for sentiment-analysis
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getVersionsTextTextSentimentAnalysisGet(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        getVersionsTextTextSentimentAnalysisGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get list of models available for sentiment-analysis
     - GET /text/text/sentiment-analysis/
     - returns: RequestBuilder<AnyObject> 
     */
    public class func getVersionsTextTextSentimentAnalysisGetWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/text/text/sentiment-analysis/"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
