//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Alamofire



public class UsersAPI: APIBase {
    /**
     Read User Me
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func readUserMeImageImageUncolorizationUsersMeGet(completion: ((data: AnyObject?, error: ErrorType?) -> Void)) {
        readUserMeImageImageUncolorizationUsersMeGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Read User Me
     - GET /image/image/uncolorization/users/me
     - returns: RequestBuilder<AnyObject> 
     */
    public class func readUserMeImageImageUncolorizationUsersMeGetWithRequestBuilder() -> RequestBuilder<AnyObject> {
        let path = "/image/image/uncolorization/users/me"
        let URLString = OpenAPIClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<AnyObject>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
