export * from './imageImageBackgroundRemovalApi';
import { ImageImageBackgroundRemovalApi } from './imageImageBackgroundRemovalApi';
export * from './imageImageColorizationApi';
import { ImageImageColorizationApi } from './imageImageColorizationApi';
export * from './imageImageFaceBluringApi';
import { ImageImageFaceBluringApi } from './imageImageFaceBluringApi';
export * from './imageImageRestorationApi';
import { ImageImageRestorationApi } from './imageImageRestorationApi';
export * from './imageImageSuperResolutionApi';
import { ImageImageSuperResolutionApi } from './imageImageSuperResolutionApi';
export * from './imageImageUncolorizationApi';
import { ImageImageUncolorizationApi } from './imageImageUncolorizationApi';
export * from './textTextAutocorrectApi';
import { TextTextAutocorrectApi } from './textTextAutocorrectApi';
export * from './textTextBooleanQuestionGenerationApi';
import { TextTextBooleanQuestionGenerationApi } from './textTextBooleanQuestionGenerationApi';
export * from './textTextDependencyTrackingApi';
import { TextTextDependencyTrackingApi } from './textTextDependencyTrackingApi';
export * from './textTextEmotionRecognitionApi';
import { TextTextEmotionRecognitionApi } from './textTextEmotionRecognitionApi';
export * from './textTextEntityExtractionApi';
import { TextTextEntityExtractionApi } from './textTextEntityExtractionApi';
export * from './textTextHateSpeechDetectionApi';
import { TextTextHateSpeechDetectionApi } from './textTextHateSpeechDetectionApi';
export * from './textTextKeywordExtractionApi';
import { TextTextKeywordExtractionApi } from './textTextKeywordExtractionApi';
export * from './textTextLanguageDetectionApi';
import { TextTextLanguageDetectionApi } from './textTextLanguageDetectionApi';
export * from './textTextLanguageGenerationApi';
import { TextTextLanguageGenerationApi } from './textTextLanguageGenerationApi';
export * from './textTextLemmatizationApi';
import { TextTextLemmatizationApi } from './textTextLemmatizationApi';
export * from './textTextNamedEntityRecognitionApi';
import { TextTextNamedEntityRecognitionApi } from './textTextNamedEntityRecognitionApi';
export * from './textTextNextSentencePredictionApi';
import { TextTextNextSentencePredictionApi } from './textTextNextSentencePredictionApi';
export * from './textTextNextWordPredictionApi';
import { TextTextNextWordPredictionApi } from './textTextNextWordPredictionApi';
export * from './textTextPluralApi';
import { TextTextPluralApi } from './textTextPluralApi';
export * from './textTextProgrammingLanguageGenerationApi';
import { TextTextProgrammingLanguageGenerationApi } from './textTextProgrammingLanguageGenerationApi';
export * from './textTextProgrammingLanguageIdentificationApi';
import { TextTextProgrammingLanguageIdentificationApi } from './textTextProgrammingLanguageIdentificationApi';
export * from './textTextQuestionAnsweringApi';
import { TextTextQuestionAnsweringApi } from './textTextQuestionAnsweringApi';
export * from './textTextSentencePairModelingApi';
import { TextTextSentencePairModelingApi } from './textTextSentencePairModelingApi';
export * from './textTextSentenceParaphraserApi';
import { TextTextSentenceParaphraserApi } from './textTextSentenceParaphraserApi';
export * from './textTextSentimentAnalysisApi';
import { TextTextSentimentAnalysisApi } from './textTextSentimentAnalysisApi';
export * from './textTextSimilarityApi';
import { TextTextSimilarityApi } from './textTextSimilarityApi';
export * from './textTextSummarizationApi';
import { TextTextSummarizationApi } from './textTextSummarizationApi';
export * from './textTextTranslationApi';
import { TextTextTranslationApi } from './textTextTranslationApi';
export * from './textTextTransliterationApi';
import { TextTextTransliterationApi } from './textTextTransliterationApi';
export * from './textTextWordAlignmentApi';
import { TextTextWordAlignmentApi } from './textTextWordAlignmentApi';
export const APIS = [ImageImageBackgroundRemovalApi, ImageImageColorizationApi, ImageImageFaceBluringApi, ImageImageRestorationApi, ImageImageSuperResolutionApi, ImageImageUncolorizationApi, TextTextAutocorrectApi, TextTextBooleanQuestionGenerationApi, TextTextDependencyTrackingApi, TextTextEmotionRecognitionApi, TextTextEntityExtractionApi, TextTextHateSpeechDetectionApi, TextTextKeywordExtractionApi, TextTextLanguageDetectionApi, TextTextLanguageGenerationApi, TextTextLemmatizationApi, TextTextNamedEntityRecognitionApi, TextTextNextSentencePredictionApi, TextTextNextWordPredictionApi, TextTextPluralApi, TextTextProgrammingLanguageGenerationApi, TextTextProgrammingLanguageIdentificationApi, TextTextQuestionAnsweringApi, TextTextSentencePairModelingApi, TextTextSentenceParaphraserApi, TextTextSentimentAnalysisApi, TextTextSimilarityApi, TextTextSummarizationApi, TextTextTranslationApi, TextTextTransliterationApi, TextTextWordAlignmentApi];
