export * from './imageImageBackgroundRemoval.service';
import { ImageImageBackgroundRemovalService } from './imageImageBackgroundRemoval.service';
export * from './imageImageColorization.service';
import { ImageImageColorizationService } from './imageImageColorization.service';
export * from './imageImageFaceBluring.service';
import { ImageImageFaceBluringService } from './imageImageFaceBluring.service';
export * from './imageImageRestoration.service';
import { ImageImageRestorationService } from './imageImageRestoration.service';
export * from './imageImageSuperResolution.service';
import { ImageImageSuperResolutionService } from './imageImageSuperResolution.service';
export * from './imageImageUncolorization.service';
import { ImageImageUncolorizationService } from './imageImageUncolorization.service';
export * from './textTextAutocorrect.service';
import { TextTextAutocorrectService } from './textTextAutocorrect.service';
export * from './textTextBooleanQuestionGeneration.service';
import { TextTextBooleanQuestionGenerationService } from './textTextBooleanQuestionGeneration.service';
export * from './textTextDependencyTracking.service';
import { TextTextDependencyTrackingService } from './textTextDependencyTracking.service';
export * from './textTextEmotionRecognition.service';
import { TextTextEmotionRecognitionService } from './textTextEmotionRecognition.service';
export * from './textTextEntityExtraction.service';
import { TextTextEntityExtractionService } from './textTextEntityExtraction.service';
export * from './textTextHateSpeechDetection.service';
import { TextTextHateSpeechDetectionService } from './textTextHateSpeechDetection.service';
export * from './textTextKeywordExtraction.service';
import { TextTextKeywordExtractionService } from './textTextKeywordExtraction.service';
export * from './textTextLanguageDetection.service';
import { TextTextLanguageDetectionService } from './textTextLanguageDetection.service';
export * from './textTextLanguageGeneration.service';
import { TextTextLanguageGenerationService } from './textTextLanguageGeneration.service';
export * from './textTextLemmatization.service';
import { TextTextLemmatizationService } from './textTextLemmatization.service';
export * from './textTextNamedEntityRecognition.service';
import { TextTextNamedEntityRecognitionService } from './textTextNamedEntityRecognition.service';
export * from './textTextNextSentencePrediction.service';
import { TextTextNextSentencePredictionService } from './textTextNextSentencePrediction.service';
export * from './textTextNextWordPrediction.service';
import { TextTextNextWordPredictionService } from './textTextNextWordPrediction.service';
export * from './textTextPlural.service';
import { TextTextPluralService } from './textTextPlural.service';
export * from './textTextProgrammingLanguageGeneration.service';
import { TextTextProgrammingLanguageGenerationService } from './textTextProgrammingLanguageGeneration.service';
export * from './textTextProgrammingLanguageIdentification.service';
import { TextTextProgrammingLanguageIdentificationService } from './textTextProgrammingLanguageIdentification.service';
export * from './textTextQuestionAnswering.service';
import { TextTextQuestionAnsweringService } from './textTextQuestionAnswering.service';
export * from './textTextSentencePairModeling.service';
import { TextTextSentencePairModelingService } from './textTextSentencePairModeling.service';
export * from './textTextSentenceParaphraser.service';
import { TextTextSentenceParaphraserService } from './textTextSentenceParaphraser.service';
export * from './textTextSentimentAnalysis.service';
import { TextTextSentimentAnalysisService } from './textTextSentimentAnalysis.service';
export * from './textTextSimilarity.service';
import { TextTextSimilarityService } from './textTextSimilarity.service';
export * from './textTextSummarization.service';
import { TextTextSummarizationService } from './textTextSummarization.service';
export * from './textTextTranslation.service';
import { TextTextTranslationService } from './textTextTranslation.service';
export * from './textTextTransliteration.service';
import { TextTextTransliterationService } from './textTextTransliteration.service';
export * from './textTextWordAlignment.service';
import { TextTextWordAlignmentService } from './textTextWordAlignment.service';
export const APIS = [ImageImageBackgroundRemovalService, ImageImageColorizationService, ImageImageFaceBluringService, ImageImageRestorationService, ImageImageSuperResolutionService, ImageImageUncolorizationService, TextTextAutocorrectService, TextTextBooleanQuestionGenerationService, TextTextDependencyTrackingService, TextTextEmotionRecognitionService, TextTextEntityExtractionService, TextTextHateSpeechDetectionService, TextTextKeywordExtractionService, TextTextLanguageDetectionService, TextTextLanguageGenerationService, TextTextLemmatizationService, TextTextNamedEntityRecognitionService, TextTextNextSentencePredictionService, TextTextNextWordPredictionService, TextTextPluralService, TextTextProgrammingLanguageGenerationService, TextTextProgrammingLanguageIdentificationService, TextTextQuestionAnsweringService, TextTextSentencePairModelingService, TextTextSentenceParaphraserService, TextTextSentimentAnalysisService, TextTextSimilarityService, TextTextSummarizationService, TextTextTranslationService, TextTextTransliterationService, TextTextWordAlignmentService];
