// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime';
import {
    ValidationError,
    ValidationErrorFromJSON,
    ValidationErrorToJSON,
} from './';

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    detail?: Array<ValidationError>;
}

export function HTTPValidationErrorFromJSON(json: any): HTTPValidationError {
    return {
        'detail': !exists(json, 'detail') ? undefined : (json['detail'] as Array<any>).map(ValidationErrorFromJSON),
    };
}

export function HTTPValidationErrorToJSON(value?: HTTPValidationError): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'detail': value.detail === undefined ? undefined : (value.detail as Array<any>).map(ValidationErrorToJSON),
    };
}


