#import <Foundation/Foundation.h>
#import "OAIHTTPValidationError.h"
#import "OAIApi.h"

/**
* FastAPI
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAITextTextAutocorrectApi: NSObject <OAIApi>

extern NSString* kOAITextTextAutocorrectApiErrorDomain;
extern NSInteger kOAITextTextAutocorrectApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Apply model for the autocorrect task for a given models
/// 
///
/// @param sentence  (optional) (default to @"Text to corrcte")
/// @param model  (optional) (default to @"flexudy-t5-base-multi-sentence-doctor")
/// 
///  code:200 message:"Successful Response",
///  code:422 message:"Validation Error"
///
/// @return NSObject*
-(NSURLSessionTask*) applyTextTextAutocorrectPostWithSentence: (NSString*) sentence
    model: (NSString*) model
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Get list of models available for autocorrect
/// 
///
/// 
///  code:200 message:"Successful Response"
///
/// @return NSObject*
-(NSURLSessionTask*) getVersionsTextTextAutocorrectGetWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;



@end
