#import <Foundation/Foundation.h>
#import "OAIHTTPValidationError.h"
#import "OAIApi.h"

/**
* FastAPI
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAITextTextLanguageGenerationApi: NSObject <OAIApi>

extern NSString* kOAITextTextLanguageGenerationApiErrorDomain;
extern NSInteger kOAITextTextLanguageGenerationApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Apply model for the language-generation task for a given models
/// 
///
/// @param text  (optional) (default to @"Input text to start generation from")
/// @param model  (optional) (default to @"EleutherAI-gpt-neo-2_7B")
/// 
///  code:200 message:"Successful Response",
///  code:422 message:"Validation Error"
///
/// @return NSObject*
-(NSURLSessionTask*) applyTextTextLanguageGenerationPostWithText: (NSString*) text
    model: (NSString*) model
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Get list of models available for language-generation
/// 
///
/// 
///  code:200 message:"Successful Response"
///
/// @return NSObject*
-(NSURLSessionTask*) getVersionsTextTextLanguageGenerationGetWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;



@end
