// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    HTTPValidationError,
} from '../models';

export interface ApplyTextTextBooleanQuestionGenerationPostRequest {
    text?: string;
    model?: ApplyTextTextBooleanQuestionGenerationPostModelEnum;
}

/**
 * no description
 */
export class TextTextBooleanQuestionGenerationApi extends BaseAPI {

    /**
     * Apply model for the boolean-question-generation task for a given models
     */
    applyTextTextBooleanQuestionGenerationPost(requestParameters: ApplyTextTextBooleanQuestionGenerationPostRequest): Observable<object> {
        const queryParameters: HttpQuery = {};

        if (requestParameters.text !== undefined && requestParameters.text !== null) {
            queryParameters['text'] = requestParameters.text;
        }

        if (requestParameters.model !== undefined && requestParameters.model !== null) {
            queryParameters['model'] = requestParameters.model;
        }

        const headerParameters: HttpHeaders = {};

        return this.request<object>({
            path: `/text/text/boolean-question-generation/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     * Get list of models available for boolean-question-generation
     */
    getVersionsTextTextBooleanQuestionGenerationGet(): Observable<object> {
        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        return this.request<object>({
            path: `/text/text/boolean-question-generation/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ApplyTextTextBooleanQuestionGenerationPostModelEnum {
    Questgen = 'questgen'
}
