// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    HTTPValidationError,
} from '../models';

export interface ApplyTextTextTranslationPostRequest {
    inputString?: string;
    sourceLanguage?: string;
    targetLanguage?: string;
    model?: ApplyTextTextTranslationPostModelEnum;
}

/**
 * no description
 */
export class TextTextTranslationApi extends BaseAPI {

    /**
     * Apply model for the translation task for a given models
     */
    applyTextTextTranslationPost(requestParameters: ApplyTextTextTranslationPostRequest): Observable<object> {
        const queryParameters: HttpQuery = {};

        if (requestParameters.inputString !== undefined && requestParameters.inputString !== null) {
            queryParameters['input_string'] = requestParameters.inputString;
        }

        if (requestParameters.sourceLanguage !== undefined && requestParameters.sourceLanguage !== null) {
            queryParameters['source_language'] = requestParameters.sourceLanguage;
        }

        if (requestParameters.targetLanguage !== undefined && requestParameters.targetLanguage !== null) {
            queryParameters['target_language'] = requestParameters.targetLanguage;
        }

        if (requestParameters.model !== undefined && requestParameters.model !== null) {
            queryParameters['model'] = requestParameters.model;
        }

        const headerParameters: HttpHeaders = {};

        return this.request<object>({
            path: `/text/text/translation/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     * Get list of models available for translation
     */
    getVersionsTextTextTranslationGet(): Observable<object> {
        const queryParameters: HttpQuery = {};

        const headerParameters: HttpHeaders = {};

        return this.request<object>({
            path: `/text/text/translation/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ApplyTextTextTranslationPostModelEnum {
    HelsinkiNLP = 'Helsinki-NLP'
}
