/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.HTTPValidationError
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object TextTextWordAlignmentApi {

  def apply(baseUrl: String = "http://localhost") = new TextTextWordAlignmentApi(baseUrl)
}

class TextTextWordAlignmentApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : Any (Successful Response)
   *   code 422 : HTTPValidationError (Validation Error)
   * 
   * @param inputStringLanguage1 
   * @param inputStringLanguage2 
   * @param model 
   */
  def applyTextTextWordAlignmentPost(inputStringLanguage1: Option[String] = None, inputStringLanguage2: Option[String] = None, model: Option[String] = None): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.POST, "http://localhost", "/text/text/word-alignment/", "application/json")
      .withQueryParam("input_string_language_1", inputStringLanguage1)
      .withQueryParam("input_string_language_2", inputStringLanguage2)
      .withQueryParam("model", model)
      .withSuccessResponse[Any](200)
      .withErrorResponse[HTTPValidationError](422)
      

  /**
   * Expected answers:
   *   code 200 : Any (Successful Response)
   */
  def getVersionsTextTextWordAlignmentGet(): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.GET, "http://localhost", "/text/text/word-alignment/", "application/json")
      .withSuccessResponse[Any](200)
      



}

