/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.HTTPValidationError
import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object TextTextTranslationApi {

  def apply(baseUrl: String = "http://localhost") = new TextTextTranslationApi(baseUrl)
}

class TextTextTranslationApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : Any (Successful Response)
   *   code 422 : HTTPValidationError (Validation Error)
   * 
   * @param inputString 
   * @param sourceLanguage 
   * @param targetLanguage 
   * @param model 
   */
  def applyTextTextTranslationPost(inputString: Option[String] = None, sourceLanguage: Option[String] = None, targetLanguage: Option[String] = None, model: Option[String] = None): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.POST, "http://localhost", "/text/text/translation/", "application/json")
      .withQueryParam("input_string", inputString)
      .withQueryParam("source_language", sourceLanguage)
      .withQueryParam("target_language", targetLanguage)
      .withQueryParam("model", model)
      .withSuccessResponse[Any](200)
      .withErrorResponse[HTTPValidationError](422)
      

  /**
   * Expected answers:
   *   code 200 : Any (Successful Response)
   */
  def getVersionsTextTextTranslationGet(): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.GET, "http://localhost", "/text/text/translation/", "application/json")
      .withSuccessResponse[Any](200)
      



}

