/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.core._
import org.openapitools.client.core.CollectionFormats._
import org.openapitools.client.core.ApiKeyLocations._

object UsersApi {

  def apply(baseUrl: String = "http://localhost") = new UsersApi(baseUrl)
}

class UsersApi(baseUrl: String) {
  
  /**
   * Expected answers:
   *   code 200 : Any (Successful Response)
   */
  def readUserMeImageImageUncolorizationUsersMeGet(): ApiRequest[Any] =
    ApiRequest[Any](ApiMethods.GET, "http://localhost", "/image/image/uncolorization/users/me", "application/json")
      .withSuccessResponse[Any](200)
      



}

