--[[
  FastAPI
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  The version of the OpenAPI document: 0.1.0
  
  Generated by: https://openapi-generator.tech
]]

-- validation_error class
local validation_error = {}
local validation_error_mt = {
	__name = "validation_error";
	__index = validation_error;
}

local function cast_validation_error(t)
	return setmetatable(t, validation_error_mt)
end

local function new_validation_error(loc, msg, type)
	return cast_validation_error({
		["loc"] = loc;
		["msg"] = msg;
		["type"] = type;
	})
end

return {
	cast = cast_validation_error;
	new = new_validation_error;
}
