{-
   FastAPI
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   The version of the OpenAPI document: 0.1.0

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.ImageImageFaceBluring exposing (applyImageImageFaceBluringPost, getVersionsImageImageFaceBluringGet)

import Data.HTTPValidationError as HTTPValidationError exposing (HTTPValidationError)
import Data.Object as Object exposing (Object)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url


basePath : String
basePath =
    "http://localhost"


applyImageImageFaceBluringPost :
    { onSend : Result Http.Error Object -> msg




    , model : Maybe (String)
    }
    -> Cmd msg
applyImageImageFaceBluringPost params =
    Http.request
        { method = "POST"
        , headers = []
        , url = Url.crossOrigin basePath
            ["image", "image", "face-bluring"]
            (List.filterMap identity [Maybe.map (Url.string "model" ) params.model])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend Object.decoder
        , timeout = Just 30000
        , tracker = Nothing
        }


getVersionsImageImageFaceBluringGet :
    { onSend : Result Http.Error Object -> msg





    }
    -> Cmd msg
getVersionsImageImageFaceBluringGet params =
    Http.request
        { method = "GET"
        , headers = []
        , url = Url.crossOrigin basePath
            ["image", "image", "face-bluring"]
            []
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend Object.decoder
        , timeout = Just 30000
        , tracker = Nothing
        }
