#!/usr/bin/env bash
if [ -z "$1" ]; then
    env="dev"
else
    env=$1
fi
if [ "$env" = "dev" ] || [ "$env" = "prod" ]; then
    docker build --target $env -t gladiaio/gladia -f gpu.Dockerfile .
    if [ "$env" = "prod" ];then
        env="latest"
    fi
    docker tag $env gladiaio/gladia
    docker push gladiaio/gladia
fi
