note
 description:"[
		FastAPI
 		No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  		The version of the OpenAPI document: 0.1.0
 	    

  	NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

 		 Do not edit the class manually.
 	]"
	date: "$Date$"
	revision: "$Revision$"
	EIS:"Eiffel openapi generator", "src=https://openapi-generator.tech", "protocol=uri"
class HTTP_VALIDATION_ERROR 

inherit

  ANY
      redefine
          out 
      end


feature --Access

    detail: detachable LIST [VALIDATION_ERROR] 
      

feature -- Change Element  
 
    set_detail (a_name: like detail)
        -- Set 'detail' with 'a_name'.
      do
        detail := a_name
      ensure
        detail_set: detail = a_name		
      end


 feature -- Status Report

    out: STRING
          -- <Precursor>
      do
        create Result.make_empty
        Result.append("%Nclass HTTP_VALIDATION_ERROR%N")
        if attached detail as l_detail then
          across l_detail as ic loop
            Result.append ("%N detail:")
            Result.append (ic.item.out)
            Result.append ("%N")
          end
        end 
      end
end


