//
// TextTextSentimentAnalysisAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire



open class TextTextSentimentAnalysisAPI {
    /**
     * enum for parameter model
     */
    public enum Model_applyTextTextSentimentAnalysisPost: String {
        case nlptownBertBaseMultilingualUncasedSentiment = "nlptown-bert-base-multilingual-uncased-sentiment"
        case distilbertBaseUncased = "distilbert-base-uncased"
        case distilbertBaseUncasedFinetunedSst2English = "distilbert-base-uncased-finetuned-sst-2-english"
        case zeroShotClassificationFacebookBartLargeMnli = "zero-shot-classification-facebook-bart-large-mnli"
    }

    /**
     Apply model for the sentiment-analysis task for a given models
     
     - parameter text: (query)  (optional, default to "I like you. I love you")
     - parameter model: (query)  (optional, default to .distilbert-base-uncased-finetuned-sst-2-english)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func applyTextTextSentimentAnalysisPost(text: String? = nil, model: Model_applyTextTextSentimentAnalysisPost? = nil, completion: @escaping ((_ data: Any?,_ error: Error?) -> Void)) {
        applyTextTextSentimentAnalysisPostWithRequestBuilder(text: text, model: model).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Apply model for the sentiment-analysis task for a given models
     - POST /text/text/sentiment-analysis/
     - parameter text: (query)  (optional, default to "I like you. I love you")
     - parameter model: (query)  (optional, default to .distilbert-base-uncased-finetuned-sst-2-english)
     - returns: RequestBuilder<Any> 
     */
    open class func applyTextTextSentimentAnalysisPostWithRequestBuilder(text: String? = nil, model: Model_applyTextTextSentimentAnalysisPost? = nil) -> RequestBuilder<Any> {
        let path = "/text/text/sentiment-analysis/"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "text": text, 
            "model": model?.rawValue
        ])

        let requestBuilder: RequestBuilder<Any>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get list of models available for sentiment-analysis
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getVersionsTextTextSentimentAnalysisGet(completion: @escaping ((_ data: Any?,_ error: Error?) -> Void)) {
        getVersionsTextTextSentimentAnalysisGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Get list of models available for sentiment-analysis
     - GET /text/text/sentiment-analysis/
     - returns: RequestBuilder<Any> 
     */
    open class func getVersionsTextTextSentimentAnalysisGetWithRequestBuilder() -> RequestBuilder<Any> {
        let path = "/text/text/sentiment-analysis/"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Any>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
