// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models';

export interface ApplyTextTextSentencePairModelingPostRequest {
    sentence?: string;
    model?: string;
}

/**
 * no description
 */
export class TextTextSentencePairModelingApi extends runtime.BaseAPI {

    /**
     * Apply model for the sentence-pair-modeling task for a given models
     */
    async applyTextTextSentencePairModelingPostRaw(requestParameters: ApplyTextTextSentencePairModelingPostRequest): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.sentence !== undefined) {
            queryParameters['sentence'] = requestParameters.sentence;
        }

        if (requestParameters.model !== undefined) {
            queryParameters['model'] = requestParameters.model;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/sentence-pair-modeling/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Apply model for the sentence-pair-modeling task for a given models
     */
    async applyTextTextSentencePairModelingPost(requestParameters: ApplyTextTextSentencePairModelingPostRequest): Promise<object> {
        const response = await this.applyTextTextSentencePairModelingPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get list of models available for sentence-pair-modeling
     */
    async getVersionsTextTextSentencePairModelingGetRaw(): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/sentence-pair-modeling/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Get list of models available for sentence-pair-modeling
     */
    async getVersionsTextTextSentencePairModelingGet(): Promise<object> {
        const response = await this.getVersionsTextTextSentencePairModelingGetRaw();
        return await response.value();
    }

}
