// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models';

export interface ApplyTextTextLemmatizationPostRequest {
    sentence?: string;
    model?: ApplyTextTextLemmatizationPostModelEnum;
}

/**
 * no description
 */
export class TextTextLemmatizationApi extends runtime.BaseAPI {

    /**
     * Apply model for the lemmatization task for a given models
     */
    async applyTextTextLemmatizationPostRaw(requestParameters: ApplyTextTextLemmatizationPostRequest): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.sentence !== undefined) {
            queryParameters['sentence'] = requestParameters.sentence;
        }

        if (requestParameters.model !== undefined) {
            queryParameters['model'] = requestParameters.model;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/lemmatization/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Apply model for the lemmatization task for a given models
     */
    async applyTextTextLemmatizationPost(requestParameters: ApplyTextTextLemmatizationPostRequest): Promise<object> {
        const response = await this.applyTextTextLemmatizationPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get list of models available for lemmatization
     */
    async getVersionsTextTextLemmatizationGetRaw(): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/lemmatization/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Get list of models available for lemmatization
     */
    async getVersionsTextTextLemmatizationGet(): Promise<object> {
        const response = await this.getVersionsTextTextLemmatizationGetRaw();
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ApplyTextTextLemmatizationPostModelEnum {
    Wordnet = 'wordnet'
}
