// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models';

export interface ApplyTextTextSentenceParaphraserPostRequest {
    context?: string;
    model?: ApplyTextTextSentenceParaphraserPostModelEnum;
}

/**
 * no description
 */
export class TextTextSentenceParaphraserApi extends runtime.BaseAPI {

    /**
     * Apply model for the sentence-paraphraser task for a given models
     */
    async applyTextTextSentenceParaphraserPostRaw(requestParameters: ApplyTextTextSentenceParaphraserPostRequest): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.context !== undefined) {
            queryParameters['context'] = requestParameters.context;
        }

        if (requestParameters.model !== undefined) {
            queryParameters['model'] = requestParameters.model;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/sentence-paraphraser/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Apply model for the sentence-paraphraser task for a given models
     */
    async applyTextTextSentenceParaphraserPost(requestParameters: ApplyTextTextSentenceParaphraserPostRequest): Promise<object> {
        const response = await this.applyTextTextSentenceParaphraserPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get list of models available for sentence-paraphraser
     */
    async getVersionsTextTextSentenceParaphraserGetRaw(): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/sentence-paraphraser/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Get list of models available for sentence-paraphraser
     */
    async getVersionsTextTextSentenceParaphraserGet(): Promise<object> {
        const response = await this.getVersionsTextTextSentenceParaphraserGetRaw();
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ApplyTextTextSentenceParaphraserPostModelEnum {
    RamsrigouthamgT5LargeParaphraserDiverseHighQuality = 'ramsrigouthamg-t5-large-paraphraser-diverse-high-quality'
}
