// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models';

export interface ApplyTextTextPluralPostRequest {
    word?: string;
    count?: number;
    model?: ApplyTextTextPluralPostModelEnum;
}

/**
 * no description
 */
export class TextTextPluralApi extends runtime.BaseAPI {

    /**
     * Apply model for the plural task for a given models
     */
    async applyTextTextPluralPostRaw(requestParameters: ApplyTextTextPluralPostRequest): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.word !== undefined) {
            queryParameters['word'] = requestParameters.word;
        }

        if (requestParameters.count !== undefined) {
            queryParameters['count'] = requestParameters.count;
        }

        if (requestParameters.model !== undefined) {
            queryParameters['model'] = requestParameters.model;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/plural/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Apply model for the plural task for a given models
     */
    async applyTextTextPluralPost(requestParameters: ApplyTextTextPluralPostRequest): Promise<object> {
        const response = await this.applyTextTextPluralPostRaw(requestParameters);
        return await response.value();
    }

    /**
     * Get list of models available for plural
     */
    async getVersionsTextTextPluralGetRaw(): Promise<runtime.ApiResponse<object>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/text/text/plural/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.TextApiResponse(response);
    }

    /**
     * Get list of models available for plural
     */
    async getVersionsTextTextPluralGet(): Promise<object> {
        const response = await this.getVersionsTextTextPluralGetRaw();
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ApplyTextTextPluralPostModelEnum {
    Inflect = 'inflect'
}
