/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TextTextWordAlignmentApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_TextTextWordAlignmentApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_TextTextWordAlignmentApi_H_


#include "../ApiClient.h"

#include "HTTPValidationError.h"
#include "Object.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  TextTextWordAlignmentApi 
{
public:

    explicit TextTextWordAlignmentApi( std::shared_ptr<ApiClient> apiClient );

    virtual ~TextTextWordAlignmentApi();

    /// <summary>
    /// Apply model for the word-alignment task for a given models
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="inputStringLanguage1"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="inputStringLanguage2"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="model"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<Object>> applyTextTextWordAlignmentPost(
        boost::optional<utility::string_t> inputStringLanguage1,
        boost::optional<utility::string_t> inputStringLanguage2,
        boost::optional<utility::string_t> model
    );
    /// <summary>
    /// Get list of models available for word-alignment
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::shared_ptr<Object>> getVersionsTextTextWordAlignmentGet(
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_TextTextWordAlignmentApi_H_ */

